const apiEndpoint = "/api";

export const loginEndpoint = `${apiEndpoint}/user/login`;
export const registerEndpoint = `${apiEndpoint}/user/register`;
export const confirmSsoEndpoint = `${apiEndpoint}/sg/sso/confirm`;
export const superGroupMappingEndpoint = `${apiEndpoint}/mappings/sg`;
export const userDetailsEndpoint = `${apiEndpoint}/user/details`;
export const userProfilePictureEndpoint = `${apiEndpoint}/user/profile_picture`;
export const changeProfilePictureEndpoint = `${apiEndpoint}/user/change_profile_picture`;
export const changeProfileFieldsEndpoint = `${apiEndpoint}/user/change_profile_fields`;
export const changeProfileFieldVisibilityEndpoint = `${apiEndpoint}/user/change_profile_visibility`;
export const publicUserProfileEndpoint = `${apiEndpoint}/user/profile`;
export const usersEndpoint = `${apiEndpoint}/users`;
export const submissionsEndpoint = `${apiEndpoint}/submissions`;
export const submissionEndpoint = `${apiEndpoint}/submission`;
export const uploadSubmissionEndpoint = `${apiEndpoint}/submission/upload`;
export const reviewsEndpoint = `${submissionEndpoint}/reviews`;
export const myReviewsEndpoint = `${apiEndpoint}/reviews/my_reviews`;
export const reviewEndpoint = `${submissionEndpoint}/review`;
export const reviewDecisionEndpoint = `${submissionEndpoint}/review/decision`;
export const getDentsEndpoint = `${submissionEndpoint}/getdents`;
export const commentEndpoint = `${reviewEndpoint}/comment`;
export const commentFileEndpoint = `${commentEndpoint}/file`;
export const fileEndpoint = `${submissionEndpoint}/file`;
export const logoutEndpoint = `${apiEndpoint}/user/logout`
export const changePasswordEndpoint = `${apiEndpoint}/user/change_password`;
export const initiateForgottenPasswordEndpoint = `${apiEndpoint}/user/initiate_forgotten_password`;
export const completeForgottenPasswordEndpoint = `${apiEndpoint}/user/complete_forgotten_password`;
export const verifyEmailEndpoint = `${apiEndpoint}/user/verify_email`;
export const addRoleEndpoint = `${apiEndpoint}/user/add_role`;
export const reportsEndpoint = `${apiEndpoint}/report/view_reports`;
export const bansEndpoint = `${apiEndpoint}/ban/view_bans`;
export const banUserEndpoint = `${apiEndpoint}/ban/ban_user`;
export const revokeBanEndpoint = `${apiEndpoint}/ban/revoke`;
export const reportUserEndpoint = `${apiEndpoint}/report/submit`;
export const banReportEndpoint = `${apiEndpoint}/report/ban`;
export const dismissReportEndpoint = `${apiEndpoint}/report/dismiss`;
export const buildNumberEndpoint = `${apiEndpoint}/metadata/build`;
export const exportSubmissionEndpoint = `${apiEndpoint}/submission/export`;
export const assignReviewersEndpoint = `${apiEndpoint}/submission/assign_reviewers`;
export const mySubmissionsEndpoint = `${apiEndpoint}/submissions/my_submissions`;
export const downloadEndpoint = `${apiEndpoint}/submission/download`;
export const publishEndpoint = `${apiEndpoint}/submission/publish`;
export const versionsEndpoint = `${apiEndpoint}/submission/versions`;
export const incrementVersionEndpoint = `${apiEndpoint}/submission/increment`;
export const submissionOfTheDayEndpoint = `${apiEndpoint}/submission/published/submission_of_the_day`;
export const publicationsEndpoint = `${apiEndpoint}/submission/published`;
export const downloadPublishedSubmissionEndpoint = (publicationId: string) => `${apiEndpoint}/submission/published/${publicationId}/download`;
export const getFeaturedSubmissions = `${apiEndpoint}/submission/published/featured`;
export const getPublicationEndpoint = (publicationId: string) => `${apiEndpoint}/submission/published/${publicationId}`;
export const dashboardEndpoint = `${apiEndpoint}/user/dashboard`;
export const supportingDocumentsEndpoint = `${apiEndpoint}/submission/supporting/document/metadata`;
export const supportingDocumentEndpoint = `${apiEndpoint}/submission/supporting/document`;
export const deleteSubmissionEndpoint = `${apiEndpoint}/submission/delete`;
export const assignCoAuthorsEndpoint = `${apiEndpoint}/submission/assign_coauthors`;
export const notificationsEndpoint = `${apiEndpoint}/notification`;
export const readNotificationEndpoint = `${apiEndpoint}/notification/read`;
export const announcementEndpoint = `${apiEndpoint}/announcement`;
export const announcementsEndpoint = `${apiEndpoint}/announcements`;
export const myPublicationsEndpoint = `${apiEndpoint}/submission/published/my_publications`;
export const privateDiscussionEndpoint = `${apiEndpoint}/discussion`;
export const postPrivateMessageEndpoint = `${apiEndpoint}/discussion/message`;
export const privateDiscussionUsersEndpoint = `${apiEndpoint}/discussion/users`;
export const privateDiscussionsEndpoint = `${apiEndpoint}/discussions`;
export const getSubmissionsWithNoReviewers = `${apiEndpoint}/submissions/no_reviewers`;
export const postCreateSubmissionFromGitHub = `${apiEndpoint}/submission/upload/github`;
export const deleteSupportingDocumentEndpoint = `${apiEndpoint}/submission/supporting/document/delete`;
export const themeEndpoint = `${apiEndpoint}/user/theme`;
export const team15ThemeEndpoint = `${apiEndpoint}/user/theme/team_15`;

// this works as socket.io automatically adds /socket.io
export const socketIoEndpoint = '/';

export const defaultProfileLink = "https://avatars.githubusercontent.com/u/23016414?s=200&v=4";